"use client";

/**
 * Native KDE overlay for the F1 article's posterior predictive check.
 *
 * Replaces the matplotlib PNG at outputs/posterior_predictive_check.png
 * with an interactive, dark-theme native chart so the article doesn't
 * have to ship a static screenshot.
 *
 * Both KDE curves and parameter values come from
 *   data/f1-ppc.json
 * which is regenerated by scripts/extract-f1-ppc.py from the F1 repo's
 * outputs/arviz_summary_full.txt (posterior means) and the FastF1 cache
 * (observed residuals). The KDE bandwidth math mirrors the seaborn call
 * in the source script (Gaussian / Scott's rule, bw_adjust=1.5 on the
 * posterior-predictive curve only) — see the script header for details.
 *
 * Interactivity:
 *   • Hover the chart to drop a vertical crosshair and read both densities
 *     at the hovered residual.
 *   • Click a legend swatch to toggle either layer on/off.
 */

import { useMemo, useRef, useState } from "react";
import ppcData from "@/data/f1-ppc.json";

interface Series {
  x: number[];
  y: number[];
  n: number;
  stats: {
    mean: number;
    median: number;
    sd: number;
    min: number;
    max: number;
    outsideRange: number;
  };
}

interface PpcPayload {
  observed: Series;
  posterior: Series;
  model: {
    likelihood: string;
    mu: string;
    params: {
      alpha: number;
      beta_dnf: number;
      nu: number;
      sigma: number;
    };
    nDrivers: number;
    nTeamSeasons: number;
  };
  displayRange: [number, number];
}

const payload = ppcData as unknown as PpcPayload;

const W = 900;
const H = 460;
const PAD = { top: 28, right: 28, bottom: 78, left: 64 };
const PLOT_W = W - PAD.left - PAD.right;
const PLOT_H = H - PAD.top - PAD.bottom;

const OBSERVED_STROKE = "rgb(125, 232, 248)";
const OBSERVED_FILL = "rgba(125, 232, 248, 0.18)";
const POSTERIOR_STROKE = "rgb(251, 191, 36)";
const POSTERIOR_FILL = "rgba(251, 191, 36, 0.16)";

function formatSigned(value: number, digits = 2): string {
  const fixed = value.toFixed(digits);
  if (value < 0) return fixed.replace("-", "−");
  if (value > 0) return `+${fixed}`;
  return fixed;
}

function formatDensity(value: number): string {
  return value.toFixed(3);
}

interface LegendToggleProps {
  label: string;
  active: boolean;
  fill: string;
  stroke: string;
  onToggle: () => void;
}

function LegendToggle({
  label,
  active,
  fill,
  stroke,
  onToggle,
}: LegendToggleProps) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-pressed={active}
      title={active ? `Hide ${label}` : `Show ${label}`}
      className={`group flex cursor-pointer items-center gap-2 rounded-md border px-2.5 py-1 transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-accent ${
        active
          ? "border-white/20 bg-white/[0.04] text-fg-bright hover:bg-white/[0.07]"
          : "border-white/8 bg-transparent text-fg-dim opacity-55 hover:opacity-80 hover:border-white/15"
      }`}
    >
      <span
        aria-hidden
        className="relative inline-block h-3 w-5 rounded-[2px]"
        style={{
          background: active ? fill : "transparent",
          boxShadow: `inset 0 0 0 1px ${stroke}`,
        }}
      >
        {active ? null : (
          // Diagonal slash overlaid on the swatch when the layer is hidden —
          // a clear visual "off" signal that survives at all chart sizes.
          <span
            className="absolute left-1/2 top-1/2 block h-[1.5px] w-[140%] -translate-x-1/2 -translate-y-1/2 rotate-[-28deg]"
            style={{ background: stroke }}
          />
        )}
      </span>
      <span className={active ? "" : "line-through decoration-[1.5px]"}>
        {label}
      </span>
    </button>
  );
}

export function F1PosteriorPredictive() {
  const { observed, posterior, model, displayRange } = payload;
  const [showObs, setShowObs] = useState(true);
  const [showPp, setShowPp] = useState(true);
  const [hoverX, setHoverX] = useState<number | null>(null);
  const svgRef = useRef<SVGSVGElement | null>(null);

  const { xMin, xMax, yMax, xTicks, yTicks } = useMemo(() => {
    const [lo, hi] = displayRange;
    const peakObs = Math.max(...observed.y);
    const peakPp = Math.max(...posterior.y);
    const peak = Math.max(peakObs, peakPp);
    const ceil = Math.ceil((peak + 0.005) * 50) / 50;
    const xs: number[] = [];
    for (let v = lo; v <= hi; v += 5) xs.push(v);
    const ys: number[] = [];
    for (let v = 0; v <= ceil + 1e-9; v += 0.02) ys.push(Number(v.toFixed(2)));
    return { xMin: lo, xMax: hi, yMax: ceil, xTicks: xs, yTicks: ys };
  }, [observed.y, posterior.y, displayRange]);

  const xPlot = (v: number) =>
    PAD.left + ((v - xMin) / (xMax - xMin)) * PLOT_W;
  const yPlot = (v: number) =>
    PAD.top + (1 - v / yMax) * PLOT_H;

  const buildPath = (series: Series, closed: boolean) => {
    const segments: string[] = [];
    for (let i = 0; i < series.x.length; i++) {
      const cmd = i === 0 ? "M" : "L";
      segments.push(`${cmd}${xPlot(series.x[i]).toFixed(2)},${yPlot(series.y[i]).toFixed(2)}`);
    }
    if (closed) {
      segments.push(
        `L${xPlot(series.x[series.x.length - 1]).toFixed(2)},${yPlot(0).toFixed(2)}`,
      );
      segments.push(`L${xPlot(series.x[0]).toFixed(2)},${yPlot(0).toFixed(2)}`);
      segments.push("Z");
    }
    return segments.join(" ");
  };

  const obsPath = useMemo(() => buildPath(observed, false), [observed]);
  const obsArea = useMemo(() => buildPath(observed, true), [observed]);
  const ppPath = useMemo(() => buildPath(posterior, false), [posterior]);
  const ppArea = useMemo(() => buildPath(posterior, true), [posterior]);

  const zeroX = xPlot(0);

  // ── Crosshair / hover readout ──────────────────────────────────────────
  // Map hovered residual → density on each KDE via nearest-grid lookup
  // (the grid is uniformly spaced so an index calc beats a linear scan).
  const sampleAt = (series: Series, x: number): number => {
    const n = series.x.length;
    const step = (series.x[n - 1] - series.x[0]) / (n - 1);
    const i = Math.max(0, Math.min(n - 1, Math.round((x - series.x[0]) / step)));
    return series.y[i];
  };

  const handlePointerMove = (e: React.PointerEvent<SVGSVGElement>) => {
    if (!svgRef.current) return;
    const rect = svgRef.current.getBoundingClientRect();
    const scale = W / rect.width;
    const px = (e.clientX - rect.left) * scale;
    if (px < PAD.left || px > PAD.left + PLOT_W) {
      setHoverX(null);
      return;
    }
    const dataX = xMin + ((px - PAD.left) / PLOT_W) * (xMax - xMin);
    setHoverX(Number(dataX.toFixed(2)));
  };

  const hoverObsDensity =
    hoverX !== null && showObs ? sampleAt(observed, hoverX) : null;
  const hoverPpDensity =
    hoverX !== null && showPp ? sampleAt(posterior, hoverX) : null;

  const tooltipX = hoverX !== null ? xPlot(hoverX) : 0;
  const tooltipFlip = tooltipX + 200 > W - PAD.right ? -1 : 1;

  return (
    <div className="article-chart my-12">
      <div className="liquid-glass relative overflow-hidden rounded-xl">
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-border-subtle px-4 py-2.5 sm:px-5">
          <div className="flex min-w-0 items-center gap-3">
            <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-accent-border bg-accent-soft font-mono text-[10px] text-accent">
              P
            </div>
            <div className="truncate font-mono text-[11px] uppercase tracking-[0.18em] text-fg-bright">
              Posterior Predictive Check — Residual Distribution
            </div>
          </div>
          <div className="shrink-0 font-mono text-[10.5px] uppercase tracking-[0.2em] text-fg-muted">
            {observed.n.toLocaleString()} races · ν ≈ {model.params.nu.toFixed(2)}
          </div>
        </div>

        <svg
          ref={svgRef}
          viewBox={`0 0 ${W} ${H}`}
          role="img"
          aria-label="Density overlay of observed F1 finish residuals against posterior-predictive samples from the Student-T hierarchical model. Both distributions peak just below zero and share the same heavy-tailed shape."
          className="block h-auto w-full"
          preserveAspectRatio="xMidYMid meet"
          onPointerMove={handlePointerMove}
          onPointerLeave={() => setHoverX(null)}
          style={{ touchAction: "none" }}
        >
          {yTicks.map((v) => (
            <line
              key={`yg-${v}`}
              x1={PAD.left}
              x2={PAD.left + PLOT_W}
              y1={yPlot(v)}
              y2={yPlot(v)}
              stroke={v === 0 ? "rgba(255,255,255,0.22)" : "rgba(255,255,255,0.04)"}
              strokeWidth={1}
            />
          ))}

          {xTicks.map((v) => (
            <line
              key={`xg-${v}`}
              x1={xPlot(v)}
              x2={xPlot(v)}
              y1={PAD.top}
              y2={PAD.top + PLOT_H}
              stroke={v === 0 ? "rgba(255,255,255,0.18)" : "rgba(255,255,255,0.04)"}
              strokeWidth={1}
              strokeDasharray={v === 0 ? "3 4" : undefined}
            />
          ))}

          {showPp ? (
            <>
              <path d={ppArea} fill={POSTERIOR_FILL} />
              <path
                d={ppPath}
                fill="none"
                stroke={POSTERIOR_STROKE}
                strokeWidth={2}
                strokeLinejoin="round"
              />
            </>
          ) : null}
          {showObs ? (
            <>
              <path d={obsArea} fill={OBSERVED_FILL} />
              <path
                d={obsPath}
                fill="none"
                stroke={OBSERVED_STROKE}
                strokeWidth={2}
                strokeLinejoin="round"
              />
            </>
          ) : null}

          <line
            x1={PAD.left}
            x2={PAD.left + PLOT_W}
            y1={PAD.top + PLOT_H + 0.5}
            y2={PAD.top + PLOT_H + 0.5}
            stroke="rgba(255,255,255,0.32)"
            strokeWidth={1}
          />
          <line
            x1={PAD.left + 0.5}
            x2={PAD.left + 0.5}
            y1={PAD.top}
            y2={PAD.top + PLOT_H}
            stroke="rgba(255,255,255,0.32)"
            strokeWidth={1}
          />

          {xTicks.map((v) => (
            <text
              key={`xl-${v}`}
              x={xPlot(v)}
              y={PAD.top + PLOT_H + 22}
              textAnchor="middle"
              fontFamily="var(--font-mono), ui-monospace, monospace"
              fontSize={11}
              fill="rgba(255,255,255,0.55)"
            >
              {v}
            </text>
          ))}
          {yTicks.map((v) => (
            <text
              key={`yl-${v}`}
              x={PAD.left - 10}
              y={yPlot(v)}
              textAnchor="end"
              dominantBaseline="middle"
              fontFamily="var(--font-mono), ui-monospace, monospace"
              fontSize={11}
              fill="rgba(255,255,255,0.55)"
            >
              {v.toFixed(2)}
            </text>
          ))}

          <text
            x={PAD.left + PLOT_W / 2}
            y={H - 38}
            textAnchor="middle"
            fontFamily="var(--font-mono), ui-monospace, monospace"
            fontSize={11}
            letterSpacing="0.16em"
            fill="rgba(255,255,255,0.6)"
          >
            FINISH RESIDUAL &nbsp;·&nbsp; NEGATIVE = BETTER THAN GRID EXPECTATION
          </text>
          <text
            transform={`translate(${PAD.left - 44}, ${PAD.top + PLOT_H / 2}) rotate(-90)`}
            textAnchor="middle"
            fontFamily="var(--font-mono), ui-monospace, monospace"
            fontSize={11}
            letterSpacing="0.16em"
            fill="rgba(255,255,255,0.6)"
          >
            DENSITY
          </text>

          {/* Zero-label callout (the most meaningful x value) */}
          <text
            x={zeroX}
            y={PAD.top - 8}
            textAnchor="middle"
            fontFamily="var(--font-mono), ui-monospace, monospace"
            fontSize={10}
            letterSpacing="0.14em"
            fill="rgba(255,255,255,0.5)"
          >
            0
          </text>

          {hoverX !== null ? (
            <g pointerEvents="none">
              <line
                x1={tooltipX}
                x2={tooltipX}
                y1={PAD.top}
                y2={PAD.top + PLOT_H}
                stroke="rgba(255,255,255,0.42)"
                strokeWidth={1}
                strokeDasharray="3 3"
              />
              {hoverObsDensity !== null ? (
                <circle
                  cx={tooltipX}
                  cy={yPlot(hoverObsDensity)}
                  r={4}
                  fill={OBSERVED_STROKE}
                  stroke="rgba(10,14,18,0.95)"
                  strokeWidth={1.5}
                />
              ) : null}
              {hoverPpDensity !== null ? (
                <circle
                  cx={tooltipX}
                  cy={yPlot(hoverPpDensity)}
                  r={4}
                  fill={POSTERIOR_STROKE}
                  stroke="rgba(10,14,18,0.95)"
                  strokeWidth={1.5}
                />
              ) : null}

              {(() => {
                const TW = 200;
                const rowCount =
                  (hoverObsDensity !== null ? 1 : 0) +
                  (hoverPpDensity !== null ? 1 : 0);
                const TH = 36 + rowCount * 18;
                const tx =
                  tooltipFlip > 0 ? tooltipX + 14 : tooltipX - TW - 14;
                const ty = PAD.top + 12;
                return (
                  <g>
                    <rect
                      x={tx}
                      y={ty}
                      width={TW}
                      height={TH}
                      rx={6}
                      fill="rgba(10, 14, 18, 0.96)"
                      stroke="rgba(34, 211, 238, 0.32)"
                      strokeWidth={1}
                    />
                    <text
                      x={tx + 12}
                      y={ty + 20}
                      fontFamily="var(--font-mono), ui-monospace, monospace"
                      fontSize={11.5}
                      fill="rgba(255,255,255,0.95)"
                      letterSpacing="0.05em"
                    >
                      residual {formatSigned(hoverX, 2)}
                    </text>
                    {hoverObsDensity !== null ? (
                      <g transform={`translate(${tx + 12}, ${ty + 40})`}>
                        <rect
                          x={0}
                          y={-7}
                          width={9}
                          height={9}
                          rx={1.5}
                          fill={OBSERVED_STROKE}
                        />
                        <text
                          x={16}
                          y={0}
                          fontFamily="var(--font-mono), ui-monospace, monospace"
                          fontSize={11}
                          fill="rgba(255,255,255,0.78)"
                        >
                          observed{"  "}
                          <tspan fill="rgba(255,255,255,0.95)">
                            {formatDensity(hoverObsDensity)}
                          </tspan>
                        </text>
                      </g>
                    ) : null}
                    {hoverPpDensity !== null ? (
                      <g
                        transform={`translate(${tx + 12}, ${
                          ty + 40 + (hoverObsDensity !== null ? 18 : 0)
                        })`}
                      >
                        <rect
                          x={0}
                          y={-7}
                          width={9}
                          height={9}
                          rx={1.5}
                          fill={POSTERIOR_STROKE}
                        />
                        <text
                          x={16}
                          y={0}
                          fontFamily="var(--font-mono), ui-monospace, monospace"
                          fontSize={11}
                          fill="rgba(255,255,255,0.78)"
                        >
                          posterior{"  "}
                          <tspan fill="rgba(255,255,255,0.95)">
                            {formatDensity(hoverPpDensity)}
                          </tspan>
                        </text>
                      </g>
                    ) : null}
                  </g>
                );
              })()}
            </g>
          ) : null}
        </svg>

        <div className="flex flex-wrap items-center justify-between gap-x-6 gap-y-2 border-t border-border-subtle px-4 py-2.5 sm:px-5">
          <div className="flex flex-wrap items-center gap-2 font-mono text-[10.5px] uppercase tracking-[0.18em]">
            <LegendToggle
              label="Observed"
              active={showObs}
              fill={OBSERVED_FILL}
              stroke={OBSERVED_STROKE}
              onToggle={() => setShowObs((v) => !v)}
            />
            <LegendToggle
              label="Posterior predictive"
              active={showPp}
              fill={POSTERIOR_FILL}
              stroke={POSTERIOR_STROKE}
              onToggle={() => setShowPp((v) => !v)}
            />
            <span className="ml-1 text-[10px] tracking-[0.12em] text-fg-dim normal-case">
              click to hide / show
            </span>
          </div>
          <div className="font-mono text-[10.5px] uppercase tracking-[0.18em] text-fg-dim">
            tails beyond ±20 truncated · {posterior.stats.outsideRange} of{" "}
            {posterior.n.toLocaleString()} pp samples
          </div>
        </div>
      </div>

      <dl className="mt-3 grid grid-cols-2 gap-x-6 gap-y-1.5 font-mono text-[11px] uppercase tracking-[0.16em] text-fg-dim sm:grid-cols-4">
        <div className="flex items-baseline justify-between gap-2">
          <dt>observed med</dt>
          <dd className="text-fg-bright">
            {formatSigned(observed.stats.median, 2)}
          </dd>
        </div>
        <div className="flex items-baseline justify-between gap-2">
          <dt>posterior med</dt>
          <dd className="text-fg-bright">
            {formatSigned(posterior.stats.median, 2)}
          </dd>
        </div>
        <div className="flex items-baseline justify-between gap-2">
          <dt>observed sd</dt>
          <dd className="text-fg-bright">{observed.stats.sd.toFixed(2)}</dd>
        </div>
        <div className="flex items-baseline justify-between gap-2">
          <dt>posterior sd</dt>
          <dd className="text-fg-bright">{posterior.stats.sd.toFixed(2)}</dd>
        </div>
      </dl>
    </div>
  );
}
